[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = ".netlify/functions/:splat"
  status = 200