[build]
  command = "pnpm build"
  publish = "build"
  functions = "build/netlify/functions-build"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions/"

[[redirects]]
  from = "/api/*"
  to = ".netlify/functions/:splat"
  status = 200