POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Add this",
  "date": "2022-1-17T18:39:34.091Z",
  "important": true,
  "id": 10
}

###
GET http://localhost:3001/api/notes